# Makefile for 'server' data type
#
# Topaz, May 2016

CC = gcc
CFLAGS = -Wall -pedantic -std=c11 -ggdb

server: server.o
	$(CC) $(CFLAGS) server.o -o server

server.o:

clean: 
	rm -f *~
	rm -f *.o
	rm -f server



# all: 
# 	@echo "TODO: make game_servergame_server..."

# clean:
# 	@echo "TODO: make clean game_server..."
